name: Java CI  # Name of the workflow

on: [push, pull_request]  # Trigger the workflow on every push or pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # Set up Java Development Kit (JDK)
      with:
        java-version: '17'  # Use JDK 17
        distribution: 'temurin'  # JDK distribution (Temurin is an open-source version)

    - name: Compile Java files
      run: find src -name "*.java" -print | xargs javac  # Find all Java files and compile them

    - name: Run Java Programs
      run: |
        java -cp src easy.twoSum  # Run the Java class (e.g., twoSum)
        java -cp src easy.validParentheses  # Run ValidParentheses.java
